version: '3.7'
services:
  api:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: interview/post-api
    container_name: post-api
    environment:
      - PORT=3000
    ports:
      - '3333:3000'
  nginx:
    image: interview/nginx
    container_name: nginx
    build:
      context: ./nginx
      dockerfile: ./Dockerfile
    ports:
      - '80:80'
